sudo: false
language: go

go:
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - cd gss
  - go fmt
  - cd ./../cmd/gss
  - go fmt
  - cd ./../../cmd/gss.js
  - go fmt
