sudo: false
language: go

go:
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L -s https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 -o $GOPATH/bin/dep; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/golang/dep/releases/download/v0.5.0/dep-darwin-amd64 -O $GOPATH/bin/dep; fi
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./plugins/gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/gss.js/
  - cd gss
  - go fmt
  - cd ./../cmd/gss
  - go fmt
  - cd ./../../cmd/gss.js
  - go fmt
