sudo: false
language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - tip

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get ./...
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - scripts/format.sh
  - scripts/test.sh
