sudo: false
language: go

go:
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  #- osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get ./...
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./plugins/gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/gss/
  - gometalinter --misspell-locale=US --disable-all --enable=misspell --enable=vet ./cmd/gss.js/
  - cd gss
  - go fmt
  - cd ./../cmd/gss
  - go fmt
  - cd ./../../cmd/gss.js
  - go fmt
